# Generated by Django 5.2 on 2025-05-09 03:07

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('diagnosis_title', models.CharField(max_length=255)),
                ('health_condition', models.TextField()),
                ('cause', models.TextField(default='No control suggested.')),
                ('disease_signs', models.TextField()),
                ('control_suggestions', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_prompt', models.TextField(blank=True)),
                ('diagnosis_title', models.CharField(max_length=255)),
                ('health_condition', models.TextField()),
                ('cause', models.TextField(default='No control suggested.')),
                ('disease_signs', models.TextField()),
                ('control_suggestions', models.TextField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
