# Generated by Django 5.2 on 2025-05-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeddiagnosis',
            name='control_suggestions',
            field=models.TextField(default='No control suggested'),
            preserve_default=False,
        ),
    ]
